### PR TITLE
Add link to telemetry in menu

### PR DESCRIPTION
**Pull request by mikaelrandy**
To improve telemetry exposure, add a direct link in menu bar
# TODO
- [ ] transform `telemetry.png` into SVG, with correct color (help needed)
- [ ] do the same modification in documentation template.

### CODE REVIEW

**Comment by Grummfy** [comment]
what kind of color?

**Comment by jubianchi** [comment]
we could use this one: https://octicons.github.com/icon/dashboard/

Octicons are available as svg ;)

**Comment by mikaelrandy** [comment]
My bad, i forgot to put image origin :/
I used [this one](https://commons.wikimedia.org/wiki/File:Dashboard_font_awesome.svg) (CC licence)

**Comment by mikaelrandy** [comment]
@Grummfy the same as other icons. A kind of milky white.

**Comment by Grummfy** [comment]
Thank you for your PR.

**Pull request merged**
