### PR TITLE
Hywan patch 4

### PR DESCRIPTION
**Pull request by Frewacom**

### CODE REVIEW

**Comment by mikaelrandy** [comment]
?

**Comment by Hywan** [comment]
?

**Comment by mikaelrandy** [comment]
@Hywan can you confirm you don't know what this PR is for ?
I think we should close it.

**Comment by Hywan** [comment]
I confirm.

**Comment by Hywan** [comment]
@Frewacom We assume this PR is an error, and we have consequently closed. If this is not a mistake, please, ping us.

**Pull request closed without merging**
