### PR TITLE
Add external posts (community contributions)

### PR DESCRIPTION
**Pull request by jubianchi**
See atoum/atoum-documentation#172

news

### CODE REVIEW

**Comment by agallou** [comment]
- Seems weird to have links to others posts on the same level. 
  If we go with a blog integration what about a backdated post "Activity on the community in the latest months" ?
- The articles are written in french. So in atoum.org we will have links to french articles. The feed is not separated. This could be a problem (we could have an article written in english with the links list entitled "Blogs posts in the french community" (or something like that)).

**Comment by Grummfy** [comment]
I would prefer seeing this to community part.

:+1:  for community news

**Comment by Grummfy** [comment]
some news?

**Comment by Grummfy** [comment]
up?

**Pull request closed without merging**
