### PR TITLE
Add algolia search

### PR DESCRIPTION
**Pull request by jubianchi**
This PR adds a search engine on the website:

capture d ecran 2016-01-15 a 16 04 52

This works with the awesome @algolia engine (especially [algoliasearch-jekyll])(https://github.com/algolia/algoliasearch-jekyll).

I still have to figure out why travis does not push content to the index, but for now, I can manually push content.

### CODE REVIEW

**Comment by Hywan** [comment]
Is it the final design?

**Comment by Hywan** [comment]
(awesome PR by the way :-))

**Comment by jubianchi** [comment]
@Hywan it's the actual design and I can't come up with a better one. Feel free to suggest a better one, my graphic skills are so poor :)

**Comment by jubianchi** [comment]
@Hywan I reassigned myself to this PR as I want to finish the travis part.

**Comment by jubianchi** [comment]
ok, good for me, travis is green and it correctly pushes data to the index.

**Comment by Grummfy** [comment]
good idea, thanks

**Comment by Hywan** [comment]
@jubianchi Feel free to merge when it's ready. I will work on the design later.

**Pull request merged**
